# Generated by Django 3.2.5 on 2021-07-11 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('continent_id', models.AutoField(primary_key=True, serialize=False)),
                ('continent', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=90)),
                ('hotel_standard', models.CharField(max_length=90)),
                ('hotel_description', models.CharField(max_length=90)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.city')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=60)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.continent')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.country'),
        ),
    ]
