# Generated by Django 3.2.5 on 2021-07-11 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20210711_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_id', models.AutoField(primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_departure', models.DateTimeField()),
                ('date_of_arrival', models.DateTimeField()),
                ('date_of_return', models.DateTimeField()),
                ('number_of_days_stay', models.PositiveIntegerField()),
                ('type_of_trip', models.CharField(blank=True, choices=[('Bed & Breakfast', 'BB'), ('HalfBoard', 'HB'), ('FullBoard', 'FB'), ('All Inclusive', 'AI')], max_length=30, null=True)),
                ('adult_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('children_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promoted', models.BooleanField()),
                ('total_adult_places', models.PositiveIntegerField()),
                ('total_children_places', models.PositiveIntegerField()),
                ('available_adult_places', models.PositiveIntegerField()),
                ('available_children_places', models.PositiveIntegerField()),
                ('arrival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flight_arrival', to='viewer.airport')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.country'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.continent'),
        ),
        migrations.CreateModel(
            name='TripPurchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_description', models.TextField()),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('trip_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.trip')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.city')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.city'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flight_departure', to='viewer.airport'),
        ),
        migrations.AddField(
            model_name='trip',
            name='hotel_booked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.hotel'),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='viewer.city'),
        ),
    ]
