# Generated by Django 3.2.5 on 2021-07-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_auto_20210711_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='continent',
            old_name='continent',
            new_name='continent_name',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='country',
            new_name='country_name',
        ),
    ]
