# Generated by Django 3.2.5 on 2021-07-19 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 7, 19, 22, 27, 52, 814492)),
        ),
    ]
